root: true

plugins:
  - eslint-plugin-prettier

env:
  browser: true
  node: true
  jest: true

extends:
  - airbnb-base
  - prettier
  - prettier/babel

rules:
  prettier/prettier:
    [error, { printWidth: 120, singleQuote: true, trailingComma: all }]
  no-param-reassign: off
  no-use-before-define: [error, { variables: false }]
  import/no-unresolved: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - ./*.js
        - ./script/*.js
  import/prettier-default-export: off
  no-useless-constructor: off
  no-unused-vars: off
  no-empty-function: off
  lines-between-class-members: off
